// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpfetlnompzhrulycbea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZmV0bG5vbXB6aHJ1bHljYmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTkzMjUsImV4cCI6MjA2NDczNTMyNX0.ODqRCuhTX26o8hvojgyDo5Sk8dNhBlgpOvWoL_2BHs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);